name: build

on:
  push:
    branches: [ main ]
    # Run when container or environment is changed
    paths:
        - 'jukes-micromamba/Dockerfile'
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/bsurc/jukes-micromamba:latest
          docker push ghcr.io/bsurc/jukes-micromamba:latest
